# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.WindowModal)
        MainWindow.resize(939, 576)
        MainWindow.setAutoFillBackground(True)
        MainWindow.setDockNestingEnabled(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.addButton = QtWidgets.QPushButton(self.centralwidget)
        self.addButton.setGeometry(QtCore.QRect(40, 140, 101, 41))
        self.addButton.setObjectName("addButton")
        self.upButton = QtWidgets.QPushButton(self.centralwidget)
        self.upButton.setGeometry(QtCore.QRect(40, 80, 101, 41))
        self.upButton.setObjectName("upButton")
        self.dwbutton = QtWidgets.QPushButton(self.centralwidget)
        self.dwbutton.setEnabled(False)
        self.dwbutton.setGeometry(QtCore.QRect(40, 200, 101, 41))
        self.dwbutton.setObjectName("dwbutton")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(160, 60, 20, 201))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(50, 120, 71, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(50, 180, 71, 20))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(30, 300, 871, 20))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.detail_tab = QtWidgets.QTabWidget(self.centralwidget)
        self.detail_tab.setGeometry(QtCore.QRect(210, 10, 621, 281))
        self.detail_tab.setTabPosition(QtWidgets.QTabWidget.West)
        self.detail_tab.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.detail_tab.setElideMode(QtCore.Qt.ElideNone)
        self.detail_tab.setDocumentMode(True)
        self.detail_tab.setObjectName("detail_tab")
        self.log_tab = QtWidgets.QWidget()
        self.log_tab.setObjectName("log_tab")
        self.LogText = QtWidgets.QTextEdit(self.log_tab)
        self.LogText.setGeometry(QtCore.QRect(0, 0, 601, 281))
        font = QtGui.QFont()
        font.setFamily("Lato Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.LogText.setFont(font)
        self.LogText.setAutoFillBackground(True)
        self.LogText.setReadOnly(True)
        self.LogText.setObjectName("LogText")
        self.detail_tab.addTab(self.log_tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.detText = QtWidgets.QTextEdit(self.tab_2)
        self.detText.setGeometry(QtCore.QRect(0, 0, 601, 281))
        font = QtGui.QFont()
        font.setFamily("Lato Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.detText.setFont(font)
        self.detText.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.detText.setAutoFillBackground(True)
        self.detText.setReadOnly(True)
        self.detText.setObjectName("detText")
        self.detail_tab.addTab(self.tab_2, "")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 320, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(80, 360, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(90, 400, 121, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.file_sha = QtWidgets.QLineEdit(self.centralwidget)
        self.file_sha.setGeometry(QtCore.QRect(210, 350, 661, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.file_sha.setFont(font)
        self.file_sha.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.file_sha.setText("")
        self.file_sha.setFrame(True)
        self.file_sha.setReadOnly(True)
        self.file_sha.setObjectName("file_sha")
        self.file_size = QtWidgets.QLineEdit(self.centralwidget)
        self.file_size.setGeometry(QtCore.QRect(210, 400, 351, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.file_size.setFont(font)
        self.file_size.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.file_size.setText("")
        self.file_size.setReadOnly(True)
        self.file_size.setObjectName("file_size")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(210, 460, 391, 31))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(50, 470, 151, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 939, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOption = QtWidgets.QAction(MainWindow)
        self.actionOption.setObjectName("actionOption")
        self.menuFile.addAction(self.actionOption)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.detail_tab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.addButton.setToolTip(_translate("MainWindow", "Add file to download"))
        self.addButton.setText(_translate("MainWindow", "Add File"))
        self.upButton.setToolTip(_translate("MainWindow", "Upload file details to server"))
        self.upButton.setText(_translate("MainWindow", "Upload"))
        self.dwbutton.setToolTip(_translate("MainWindow", "Start downloading"))
        self.dwbutton.setText(_translate("MainWindow", "Download"))
        self.LogText.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Lato Black\'; font-size:10pt; font-weight:600; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:18pt;\"><br /></p></body></html>"))
        self.detail_tab.setTabText(self.detail_tab.indexOf(self.log_tab), _translate("MainWindow", "Logs"))
        self.detText.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Lato Black\'; font-size:10pt; font-weight:600; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400;\"><br /></p></body></html>"))
        self.detail_tab.setTabText(self.detail_tab.indexOf(self.tab_2), _translate("MainWindow", "Details"))
        self.label_2.setText(_translate("MainWindow", "Downloading file Details: "))
        self.label_3.setText(_translate("MainWindow", "File SHA-256: "))
        self.label_4.setText(_translate("MainWindow", "File Size:"))
        self.progressBar.setToolTip(_translate("MainWindow", "Download Progress"))
        self.label_5.setText(_translate("MainWindow", "Download Status"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionOption.setText(_translate("MainWindow", "Option"))
